### PR TITLE
Help link updates [attempt #2]

### PR DESCRIPTION
**Pull request by ruthtalbot**

### CODE REVIEW

**Comment by janakdr** [comment]
Hmm, I'm not really familiar with that code. May have never worked. If it did work, we should remove the hard-coded link in navbar.html. @RamV13 ?

**Comment by RamV13** [comment]
As of #291, the `getHelpUrl` made the main help link in the navbar page specific by updating `help-a` in `loadNavbar` within `navbar.js`. Something seems to have broken this since then.

**Comment by RamV13** [comment]
Worth noting that this is broken even at head so probably not because of this change.

**Comment by RamV13** [comment]
It's because there is a one `a` with a `help-a` class and another with a `help-a` id.

**Comment by RamV13** [comment]
Ah just missed your comment cool :)

**Pull request merged**
